import type { Analysis, Draft, InboxItem, NewsletterData, ReelIdea, Track, WebsiteProposal } from "./types";

export const INBOX_ITEMS: InboxItem[] = [
	{
		id: "in_01",
		source: "x",
		handle: "@karpathy",
		title: "The rise of small specialized models vs. general-purpose giants",
		snippet:
			'Spent the morning re-reading the Phi-3 tech report. The interesting question isn\'t "can small models match GPT-4" — it\'s "what\'s the synthetic-data recipe that gets you there, and is it transferable to Arabic-speaking educational contexts?"',
		lang: "en",
		captured: "2026-04-20T03:12:00Z",
		state: "new",
		url: "x.com/karpathy/1781...",
		length: 48,
	},
	{
		id: "in_02",
		source: "youtube",
		handle: "Yannic Kilcher",
		title: 'Paper: "Textbooks Are All You Need" — revisited two years later',
		snippet:
			"A walkthrough of what held up, what didn't, and why the community quietly moved on from the Phi line of reasoning. 42-minute breakdown with paper excerpts.",
		lang: "en",
		captured: "2026-04-20T02:48:00Z",
		state: "analyzing",
		url: "youtube.com/watch?v=...",
		length: "42:10",
	},
	{
		id: "in_03",
		source: "x",
		handle: "@swyx",
		title: "The agent-loop taxonomy I keep coming back to",
		snippet:
			'Five primitives: plan, act, observe, reflect, commit. Most "agent frameworks" are just opinionated wrappers around some subset. The interesting work is in the reflect step — and almost nobody does it well.',
		lang: "en",
		captured: "2026-04-20T02:30:00Z",
		state: "draft",
		url: "x.com/swyx/1781...",
		length: 62,
	},
	{
		id: "in_04",
		source: "article",
		handle: "anthropic.com",
		title: "Building effective agents",
		snippet:
			"A pattern language for agentic systems — augmented LLMs, prompt chaining, routing, parallelization, orchestrator-workers, evaluator-optimizer. Each with tradeoffs around autonomy vs. predictability.",
		lang: "en",
		captured: "2026-04-19T22:14:00Z",
		state: "approved",
		url: "anthropic.com/research/...",
		length: "14 min read",
	},
	{
		id: "in_05",
		source: "manual",
		handle: "operator",
		title: "Concept idea: 'the orchestrator fallacy'",
		snippet:
			"Rough note from last night. People reach for multi-agent orchestration when a single well-prompted call with tools would do. Worth a template + a short reel? Tie to Foundations track, lesson on composition.",
		lang: "en",
		captured: "2026-04-19T21:02:00Z",
		state: "new",
		length: 36,
	},
	{
		id: "in_06",
		source: "x",
		handle: "@sama",
		title: "on model evals that actually matter",
		snippet:
			"Benchmark saturation says more about the benchmarks than the models at this point. The evals I care about are the ones my team won't tell me the scores on.",
		lang: "en",
		captured: "2026-04-19T18:40:00Z",
		state: "new",
		url: "x.com/sama/1781...",
		length: 28,
	},
	{
		id: "in_07",
		source: "youtube",
		handle: "3Blue1Brown",
		title: "Attention, visualized — a geometric intuition",
		snippet:
			"Grant's long-awaited follow-up on the transformer series. Attention as a soft database query, with a beautiful rotation-matrix visualization around minute 18.",
		lang: "en",
		captured: "2026-04-19T14:20:00Z",
		state: "new",
		url: "youtube.com/watch?v=...",
		length: "26:02",
	},
	{
		id: "in_08",
		source: "manual",
		handle: "operator",
		title: "Arabic AI-education glossary — v2 pass",
		snippet:
			"Review list of 94 concepts; flag the ones where the current Arabic translation feels borrowed rather than native. Candidates: embedding, latent space, alignment.",
		lang: "ar",
		captured: "2026-04-19T10:05:00Z",
		state: "new",
		length: 24,
	},
	{
		id: "in_09",
		source: "article",
		handle: "thegradient.pub",
		title: "Why evaluation is a first-class product surface",
		snippet:
			"Evals are usually treated as a research artifact. The essay's thesis: they should be an operator's dashboard — the primary way a team sees what the model is actually doing in production.",
		lang: "en",
		captured: "2026-04-19T08:30:00Z",
		state: "rejected",
		url: "thegradient.pub/evals-as-...",
		length: "9 min read",
	},
	{
		id: "in_10",
		source: "x",
		handle: "@jxmnop",
		title: "RAG is dying; long-context is not yet ready",
		snippet:
			"The gap is smaller than you think but the transition will be awkward for another 18 months. Retrieval quality is still what decides whether your app feels smart or dumb.",
		lang: "en",
		captured: "2026-04-19T06:15:00Z",
		state: "new",
		url: "x.com/jxmnop/1781...",
		length: 44,
	},
	{
		id: "in_11",
		source: "x",
		handle: "@emilymbender",
		title: "On 'reasoning' as a marketing term",
		snippet:
			"The looser the definition of reasoning, the easier it is to claim a model has it. A short thread on why product copy is drifting further from the underlying math.",
		lang: "en",
		captured: "2026-04-19T05:02:00Z",
		state: "new",
		url: "x.com/emilymbender/1781...",
		length: 33,
	},
	{
		id: "in_12",
		source: "youtube",
		handle: "Two Minute Papers",
		title: "DeepMind's new video model and what it means for short-form creators",
		snippet:
			"Five-minute tour. Notable: a Gulf-region case study at 3:40 showing Arabic title cards rendering cleanly — small but important detail for bilingual pipelines.",
		lang: "en",
		captured: "2026-04-18T22:00:00Z",
		state: "draft",
		url: "youtube.com/watch?v=...",
		length: "5:41",
	},
];

export const CONCEPTS = [
	"transformer",
	"attention",
	"tokenizer",
	"embedding",
	"context window",
	"fine-tuning",
	"RLHF",
	"agent loop",
	"tool use",
	"orchestrator",
	"evaluation",
	"synthetic data",
	"distillation",
	"RAG",
	"long-context",
	"alignment",
	"latent space",
	"chain-of-thought",
	"self-consistency",
	"reflection",
];

export const TRACKS: Track[] = ["Foundations", "Agents", "Media"];

export const ANALYSES: Analysis[] = [
	{
		id: "an_01",
		itemId: "in_02",
		provider: "claude",
		runAt: "2026-04-20T03:02:10Z",
		cost: "$0.031",
		tokens: "2,840",
		summary:
			"A two-year retrospective on Microsoft Research's 'Textbooks Are All You Need' paper, which argued that small models trained on carefully-curated synthetic 'textbook-quality' data could compete with much larger models on reasoning tasks. Kilcher's take: the core claim held for narrow benchmarks, but the generalization story was overstated.",
		concepts: ["synthetic data", "distillation", "evaluation"],
		track: "Foundations",
		tier: "medium",
		outputs: [
			{
				kind: "tweet",
				hook: "Two years on, the Phi line of reasoning is mostly vindicated — but not where its authors said it would be.",
			},
			{ kind: "reel", hook: "Why 'textbook-quality data' was the right idea for the wrong reason." },
			{
				kind: "website",
				hook: "Lesson draft: Synthetic-data recipes and the generalization gap (Foundations / Data).",
			},
		],
		keyPoints: [
			"Phi-3 is a real result, but downstream tasks requiring world-knowledge still trail larger models.",
			"The community shifted toward mixed recipes: synthetic + filtered web + domain corpora.",
			"Arabic-language synthetic data is the obvious next frontier; almost nobody is doing it at quality.",
		],
	},
];

export const DRAFTS: Draft[] = [
	{
		id: "dr_01",
		channel: "x",
		ar: "لماذا يفشل المنظم الذكي حين تحتاج إلى نموذج واحد جيد؟ خمسة مبادئ مبسّطة لفهم متى تصبح الوكلاء المتعددة عبئاً لا حلاً.",
		en: "Why the orchestrator pattern fails when you just need one good prompt — five principles for knowing when multi-agent becomes a liability.",
		state: "draft",
		frame: "hyper-square",
		sourceAnalysis: "an_01",
		concepts: ["agent loop", "orchestrator"],
		scheduled: null,
		chars: 142,
	},
	{
		id: "dr_02",
		channel: "ig-reel",
		ar: "الانتباه ليس سحراً — إنه استعلام قاعدة بيانات ناعم. شرح هندسي في 30 ثانية.",
		en: "Attention isn't magic — it's a soft database query. A 30-second geometric walkthrough.",
		state: "approved",
		frame: "hyper-vertical",
		sourceAnalysis: "an_01",
		concepts: ["attention", "transformer"],
		scheduled: "2026-04-21T09:00:00+03:00",
		chars: 88,
	},
	{
		id: "dr_03",
		channel: "tiktok",
		ar: "ثلاث طرق يستخدمها المحترفون لكتابة التعليمات — ولماذا الطريقة الأبسط عادة هي الأفضل.",
		en: "Three prompt patterns the pros use — and why the simplest one usually wins.",
		state: "draft",
		frame: "hyper-vertical",
		sourceAnalysis: "an_01",
		concepts: ["chain-of-thought"],
		scheduled: null,
		chars: 96,
	},
	{
		id: "dr_04",
		channel: "yt-shorts",
		ar: "ما الفرق بين النموذج الصغير المتخصص والنموذج العام الكبير؟ مقارنة في ستين ثانية.",
		en: "Small specialized vs. big general — a sixty-second side-by-side.",
		state: "new",
		frame: "hyper-vertical",
		sourceAnalysis: "an_01",
		concepts: ["distillation", "fine-tuning"],
		scheduled: null,
		chars: 102,
	},
	{
		id: "dr_05",
		channel: "x",
		ar: "التقييم ليس أداة بحثية — إنه سطح المنتج الأول. الفرق بين فريقٍ جيدٍ وفريقٍ عظيمٍ يظهر في كيفية قياسهم لما يصنعون.",
		en: "Evals aren't a research artifact — they're your first product surface.",
		state: "approved",
		frame: "hyper-square",
		sourceAnalysis: "an_01",
		concepts: ["evaluation"],
		scheduled: "2026-04-20T18:00:00+03:00",
		chars: 71,
	},
	{
		id: "dr_06",
		channel: "ig",
		ar: "مسرد عربي للذكاء الاصطناعي — الإصدار الثاني. أربعة مصطلحات أعدنا ترجمتها هذا الأسبوع.",
		en: "Arabic AI glossary, v2 — four terms we re-translated this week.",
		state: "draft",
		frame: "hyper-square",
		sourceAnalysis: "an_01",
		concepts: ["embedding", "latent space"],
		scheduled: null,
		chars: 84,
	},
];

export const REEL_IDEAS: ReelIdea[] = [
	{
		id: "re_01",
		hook: "Why 'reasoning' became a marketing term.",
		beats: [
			"0:00 Open on a product demo claiming 'reasoning'",
			"0:06 Cut to the underlying math — it's pattern matching with more steps",
			"0:14 The real thing would look different, and here's how",
			"0:22 CTA: what the Bannaa Agents track actually teaches",
		],
		ref: "in_11",
		length: "0:24",
		concepts: ["alignment", "chain-of-thought"],
		state: "new",
	},
	{
		id: "re_02",
		hook: "The orchestrator fallacy, in 30 seconds.",
		beats: [
			"0:00 A complicated agent diagram appears",
			"0:08 Remove boxes one at a time — end with a single call",
			"0:18 'Most of the time, that's all you needed.'",
			"0:26 End card: Foundations lesson link",
		],
		ref: "in_05",
		length: "0:30",
		concepts: ["orchestrator", "agent loop"],
		state: "draft",
	},
	{
		id: "re_03",
		hook: "Attention, drawn on a napkin.",
		beats: [
			"0:00 Dot product of Q and K, sketched live",
			"0:10 Softmax — 'make it sum to one'",
			"0:18 Weighted sum over V — 'now we have a mix'",
			"0:24 Same idea, twelve heads in parallel",
		],
		ref: "in_07",
		length: "0:28",
		concepts: ["attention"],
		state: "approved",
	},
	{
		id: "re_04",
		hook: "RAG isn't dying — your retrieval just isn't good enough.",
		beats: [
			"0:00 Long-context claim appears",
			"0:08 Real numbers: precision vs. context length tradeoff",
			"0:18 What 'good retrieval' actually means in 2026",
			"0:26 Quick demo screenshot",
		],
		ref: "in_10",
		length: "0:29",
		concepts: ["RAG", "long-context"],
		state: "new",
	},
];

export const WEBSITE_PROPOSALS: WebsiteProposal[] = [
	{
		id: "ws_01",
		path: "lib/content.ts › concepts › orchestrator",
		kind: "concept",
		track: "Agents",
		en: {
			title: "Orchestrator",
			body: "An orchestrator is a control-flow pattern in which one agent decomposes a task into sub-tasks and delegates each to a worker. It's the default framing in most agent frameworks — and it's often overkill. Before reaching for an orchestrator, ask whether a single well-prompted call with tools could do the same job. In practice, three-quarters of 'orchestrated' pipelines collapse to a single step once their real requirements become clear.",
		},
		ar: {
			title: "المنظم",
			body: "المنظم هو نمط للتحكم في تدفق المهمة، يقوم فيه وكيل واحد بتقسيم المهمة إلى مهام فرعية ثم يفوّض كل واحدة إلى عامل. هذا هو التأطير الافتراضي في معظم أطر الوكلاء — وكثيراً ما يكون مبالغاً فيه. قبل اللجوء إلى المنظم، اسأل: هل يمكن لاستدعاء واحد مُصمَّم جيداً، مزوَّد بأدوات مناسبة، أن يُنجز العمل؟ في الممارسة، ثلاثة أرباع خطوط الأنابيب «المنظَّمة» تنهار إلى خطوة واحدة حين تتضح متطلباتها الحقيقية.",
		},
		state: "draft",
		pr: null,
	},
	{
		id: "ws_02",
		path: "lib/content.ts › templates › eval-loop-minimal",
		kind: "template",
		track: "Foundations",
		en: {
			title: "Minimal eval loop",
			body: "A copy-pasteable scaffold for teams that haven't set up evaluation yet. Three files: a fixtures YAML, a runner, and a scorecard. The idea isn't to replace proper eval frameworks — it's to get you from zero to 'we can see what's broken' inside a working afternoon.",
		},
		ar: {
			title: "حلقة التقييم الدنيا",
			body: "هيكل جاهز للنسخ لمن لم يبدأوا التقييم بعد. ثلاثة ملفات: ملف اختبارات YAML، ومُشغِّل، وبطاقة نتيجة. الفكرة ليست استبدال أطر التقييم الجادة — بل الانتقال من الصفر إلى «نرى ما يَعطب» خلال ظهيرة عمل واحدة.",
		},
		state: "approved",
		pr: { number: 312, title: "content: add eval-loop-minimal template", branch: "content/eval-loop" },
	},
	{
		id: "ws_03",
		path: "blog › the-orchestrator-fallacy",
		kind: "blog",
		track: "Agents",
		en: {
			title: "The orchestrator fallacy",
			body: "A short essay arguing that most teams reach for multi-agent orchestration prematurely. Starts with a composed example, strips it down, and ends with a checklist of five questions to ask before writing your first supervisor agent.",
		},
		ar: {
			title: "مغالطة المنظم",
			body: "مقالة قصيرة تُحاجج بأن معظم الفرق تلجأ إلى تنظيم الوكلاء المتعددين قبل أوانه. تبدأ بمثال مُركَّب، ثم تُفكِّكه، وتنتهي بقائمة من خمسة أسئلة ينبغي طرحها قبل كتابة أول وكيل مشرف.",
		},
		state: "new",
		pr: null,
	},
];

export const NEWSLETTER: NewsletterData = {
	issue: 34,
	date: "2026-04-26",
	sendAt: "2026-04-26T09:00:00+03:00",
	status: "assembling",
	sections: [
		{
			kind: "lede",
			title: "This week: the orchestrator fallacy, and three templates that fix it.",
			approvedFrom: null,
		},
		{
			kind: "concept",
			title: "Concept of the week — Attention as a soft database query",
			approvedFrom: "an_01",
		},
		{
			kind: "three-picks",
			title: "Three things worth your time this week",
			approvedFrom: null,
			items: ["in_04", "in_07", "in_02"],
		},
		{
			kind: "template",
			title: "New template: Minimal eval loop (Foundations / Evaluation)",
			approvedFrom: "ws_02",
		},
		{
			kind: "arabic",
			title: "من المسرد العربي: إعادة ترجمة «latent space»",
			approvedFrom: null,
		},
		{
			kind: "sign-off",
			title: "Until next Sunday — m.",
			approvedFrom: null,
		},
	],
};
